services:
  vault-dev:
    hostname: vault
    container_name: vault-dev
    image: hashicorp/vault:latest
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-listen-address="0.0.0.0:8200" -dev-root-token-id="root"

  vault-init-dev:
    image: hashicorp/vault:latest
    container_name: vault-init-dev
    depends_on:
      - vault-dev
    environment:
      VAULT_ADDR: http://vault-dev:8200
      VAULT_TOKEN: root
    volumes:
      - ./init-vault-dev.sh:/init-vault-dev.sh:ro
    entrypoint: ""
    command: sh /init-vault-dev.sh
    restart: "no"