services:
  vault:
    hostname: vault
    container_name: vault-dev
    image: hashicorp/vault:latest
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-listen-address="0.0.0.0:8200" -dev-root-token-id="root"

  vault-init:
    image: hashicorp/vault:latest
    container_name: vault-init
    depends_on:
      - vault
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
    volumes:
      - ./init-vault.sh:/init-vault.sh:ro
    entrypoint: ""
    command: sh /init-vault.sh
    restart: "no"

  pgsql-server:
    image: postgres:15
    container_name: postgres-server
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ayofootball
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  auth-srv:
    build:
      context: .
      dockerfile: auth-service.dockerfile
    container_name: auth-srv
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - PORT=5001
      - SERVICE_URL=auth-srv
    depends_on:
      - vault
      - vault-init
      - pgsql-server
    restart: unless-stopped

  team-srv:
    build:
      context: .
      dockerfile: team-service.dockerfile
    container_name: team-srv
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - PORT=6001
      - SERVICE_URL=team-srv
    depends_on:
      - vault
      - vault-init
    restart: unless-stopped

  player-srv:
    build:
      context: .
      dockerfile: player-service.dockerfile
    container_name: player-srv
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - PORT=7001
      - SERVICE_URL=player-srv
    depends_on:
      - vault
      - vault-init
      - pgsql-server
    restart: unless-stopped

  match-srv:
    build:
      context: .
      dockerfile: match-service.dockerfile
    container_name: match-srv
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - PORT=7005
      - SERVICE_URL=match-srv
    depends_on:
      - vault
      - vault-init
      - pgsql-server
    restart: unless-stopped

  gateway-srv:
    build:
      context: .
      dockerfile: gateway-service.dockerfile
      platforms:
        - linux/amd64
    platform: linux/amd64
    container_name: gateway-srv
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    ports:
      - "8000:8000"
    depends_on:
      - auth-srv
      - team-srv
      - player-srv
      - match-srv
    restart: unless-stopped

volumes:
  postgres-data:
