// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0
// source: player.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position int32

const (
	Position_UNKNOWN        Position = 0
	Position_PENYERANG      Position = 1
	Position_GELANDANG      Position = 2
	Position_BERTAHAN       Position = 3
	Position_PENJAGA_GAWANG Position = 4
)

// Enum value maps for Position.
var (
	Position_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENYERANG",
		2: "GELANDANG",
		3: "BERTAHAN",
		4: "PENJAGA_GAWANG",
	}
	Position_value = map[string]int32{
		"UNKNOWN":        0,
		"PENYERANG":      1,
		"GELANDANG":      2,
		"BERTAHAN":       3,
		"PENJAGA_GAWANG": 4,
	}
)

func (x Position) Enum() *Position {
	p := new(Position)
	*p = x
	return p
}

func (x Position) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Position) Descriptor() protoreflect.EnumDescriptor {
	return file_player_proto_enumTypes[0].Descriptor()
}

func (Position) Type() protoreflect.EnumType {
	return &file_player_proto_enumTypes[0]
}

func (x Position) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Position.Descriptor instead.
func (Position) EnumDescriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Height        float32                `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	Weight        float32                `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Position      Position               `protobuf:"varint,6,opt,name=position,proto3,enum=Position" json:"position,omitempty"`
	BackNumber    int32                  `protobuf:"varint,7,opt,name=back_number,json=backNumber,proto3" json:"back_number,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Player) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Player) GetPosition() Position {
	if x != nil {
		return x.Position
	}
	return Position_UNKNOWN
}

func (x *Player) GetBackNumber() int32 {
	if x != nil {
		return x.BackNumber
	}
	return 0
}

func (x *Player) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Player) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Height        float32                `protobuf:"fixed32,3,opt,name=height,proto3" json:"height,omitempty"`
	Weight        float32                `protobuf:"fixed32,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Position      Position               `protobuf:"varint,5,opt,name=position,proto3,enum=Position" json:"position,omitempty"`
	BackNumber    int32                  `protobuf:"varint,6,opt,name=back_number,json=backNumber,proto3" json:"back_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerRequest) Reset() {
	*x = CreatePlayerRequest{}
	mi := &file_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerRequest) ProtoMessage() {}

func (x *CreatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlayerRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlayerRequest) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CreatePlayerRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreatePlayerRequest) GetPosition() Position {
	if x != nil {
		return x.Position
	}
	return Position_UNKNOWN
}

func (x *CreatePlayerRequest) GetBackNumber() int32 {
	if x != nil {
		return x.BackNumber
	}
	return 0
}

type UpdatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Height        float32                `protobuf:"fixed32,3,opt,name=height,proto3" json:"height,omitempty"`
	Weight        float32                `protobuf:"fixed32,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Position      Position               `protobuf:"varint,5,opt,name=position,proto3,enum=Position" json:"position,omitempty"`
	BackNumber    int32                  `protobuf:"varint,6,opt,name=back_number,json=backNumber,proto3" json:"back_number,omitempty"`
	TeamId        string                 `protobuf:"bytes,7,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerRequest) Reset() {
	*x = UpdatePlayerRequest{}
	mi := &file_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerRequest) ProtoMessage() {}

func (x *UpdatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePlayerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePlayerRequest) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UpdatePlayerRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdatePlayerRequest) GetPosition() Position {
	if x != nil {
		return x.Position
	}
	return Position_UNKNOWN
}

func (x *UpdatePlayerRequest) GetBackNumber() int32 {
	if x != nil {
		return x.BackNumber
	}
	return 0
}

func (x *UpdatePlayerRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlayerRequest) Reset() {
	*x = DeletePlayerRequest{}
	mi := &file_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlayerRequest) ProtoMessage() {}

func (x *DeletePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlayerRequest.ProtoReflect.Descriptor instead.
func (*DeletePlayerRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePlayerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPlayersByTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayersByTeamRequest) Reset() {
	*x = ListPlayersByTeamRequest{}
	mi := &file_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayersByTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayersByTeamRequest) ProtoMessage() {}

func (x *ListPlayersByTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayersByTeamRequest.ProtoReflect.Descriptor instead.
func (*ListPlayersByTeamRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{5}
}

func (x *ListPlayersByTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListPlayersByTeamRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPlayersByTeamRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayersResponse) Reset() {
	*x = ListPlayersResponse{}
	mi := &file_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayersResponse) ProtoMessage() {}

func (x *ListPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayersResponse.ProtoReflect.Descriptor instead.
func (*ListPlayersResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{6}
}

func (x *ListPlayersResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_player_proto protoreflect.FileDescriptor

const file_player_proto_rawDesc = "" +
	"\n" +
	"\fplayer.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfb\x01\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x02R\x06height\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x02R\x06weight\x12%\n" +
	"\bposition\x18\x06 \x01(\x0e2\t.PositionR\bposition\x12\x1f\n" +
	"\vback_number\x18\a \x01(\x05R\n" +
	"backNumber\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xba\x01\n" +
	"\x13CreatePlayerRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x02R\x06height\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x02R\x06weight\x12%\n" +
	"\bposition\x18\x05 \x01(\x0e2\t.PositionR\bposition\x12\x1f\n" +
	"\vback_number\x18\x06 \x01(\x05R\n" +
	"backNumber\"\xca\x01\n" +
	"\x13UpdatePlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x02R\x06height\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x02R\x06weight\x12%\n" +
	"\bposition\x18\x05 \x01(\x0e2\t.PositionR\bposition\x12\x1f\n" +
	"\vback_number\x18\x06 \x01(\x05R\n" +
	"backNumber\x12\x17\n" +
	"\ateam_id\x18\a \x01(\tR\x06teamId\"\"\n" +
	"\x10GetPlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13DeletePlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"d\n" +
	"\x18ListPlayersByTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"8\n" +
	"\x13ListPlayersResponse\x12!\n" +
	"\aplayers\x18\x01 \x03(\v2\a.PlayerR\aplayers*W\n" +
	"\bPosition\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tPENYERANG\x10\x01\x12\r\n" +
	"\tGELANDANG\x10\x02\x12\f\n" +
	"\bBERTAHAN\x10\x03\x12\x12\n" +
	"\x0ePENJAGA_GAWANG\x10\x042\x9a\x02\n" +
	"\rPlayerService\x12-\n" +
	"\fCreatePlayer\x12\x14.CreatePlayerRequest\x1a\a.Player\x12'\n" +
	"\tGetPlayer\x12\x11.GetPlayerRequest\x1a\a.Player\x12-\n" +
	"\fUpdatePlayer\x12\x14.UpdatePlayerRequest\x1a\a.Player\x12<\n" +
	"\fDeletePlayer\x12\x14.DeletePlayerRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x11ListPlayersByTeam\x12\x19.ListPlayersByTeamRequest\x1a\x14.ListPlayersResponseB@Z>github.com/apriliantocecep/ayo-football/services/player/pkg/pbb\x06proto3"

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData []byte
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)))
	})
	return file_player_proto_rawDescData
}

var file_player_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_player_proto_goTypes = []any{
	(Position)(0),                    // 0: Position
	(*Player)(nil),                   // 1: Player
	(*CreatePlayerRequest)(nil),      // 2: CreatePlayerRequest
	(*UpdatePlayerRequest)(nil),      // 3: UpdatePlayerRequest
	(*GetPlayerRequest)(nil),         // 4: GetPlayerRequest
	(*DeletePlayerRequest)(nil),      // 5: DeletePlayerRequest
	(*ListPlayersByTeamRequest)(nil), // 6: ListPlayersByTeamRequest
	(*ListPlayersResponse)(nil),      // 7: ListPlayersResponse
	(*emptypb.Empty)(nil),            // 8: google.protobuf.Empty
}
var file_player_proto_depIdxs = []int32{
	0, // 0: Player.position:type_name -> Position
	0, // 1: CreatePlayerRequest.position:type_name -> Position
	0, // 2: UpdatePlayerRequest.position:type_name -> Position
	1, // 3: ListPlayersResponse.players:type_name -> Player
	2, // 4: PlayerService.CreatePlayer:input_type -> CreatePlayerRequest
	4, // 5: PlayerService.GetPlayer:input_type -> GetPlayerRequest
	3, // 6: PlayerService.UpdatePlayer:input_type -> UpdatePlayerRequest
	5, // 7: PlayerService.DeletePlayer:input_type -> DeletePlayerRequest
	6, // 8: PlayerService.ListPlayersByTeam:input_type -> ListPlayersByTeamRequest
	1, // 9: PlayerService.CreatePlayer:output_type -> Player
	1, // 10: PlayerService.GetPlayer:output_type -> Player
	1, // 11: PlayerService.UpdatePlayer:output_type -> Player
	8, // 12: PlayerService.DeletePlayer:output_type -> google.protobuf.Empty
	7, // 13: PlayerService.ListPlayersByTeam:output_type -> ListPlayersResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		EnumInfos:         file_player_proto_enumTypes,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
