// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0
// source: moderation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArticleRequest) Reset() {
	*x = PublishArticleRequest{}
	mi := &file_moderation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArticleRequest) ProtoMessage() {}

func (x *PublishArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArticleRequest.ProtoReflect.Descriptor instead.
func (*PublishArticleRequest) Descriptor() ([]byte, []int) {
	return file_moderation_proto_rawDescGZIP(), []int{0}
}

func (x *PublishArticleRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

type PublishArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArticleResponse) Reset() {
	*x = PublishArticleResponse{}
	mi := &file_moderation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArticleResponse) ProtoMessage() {}

func (x *PublishArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArticleResponse.ProtoReflect.Descriptor instead.
func (*PublishArticleResponse) Descriptor() ([]byte, []int) {
	return file_moderation_proto_rawDescGZIP(), []int{1}
}

func (x *PublishArticleResponse) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *PublishArticleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_moderation_proto protoreflect.FileDescriptor

const file_moderation_proto_rawDesc = "" +
	"\n" +
	"\x10moderation.proto\"6\n" +
	"\x15PublishArticleRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\"O\n" +
	"\x16PublishArticleResponse\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2V\n" +
	"\x11ModerationService\x12A\n" +
	"\x0ePublishArticle\x12\x16.PublishArticleRequest\x1a\x17.PublishArticleResponseBCZAgithub.com/apriliantocecep/posfin-blog/services/moderation/pkg/pbb\x06proto3"

var (
	file_moderation_proto_rawDescOnce sync.Once
	file_moderation_proto_rawDescData []byte
)

func file_moderation_proto_rawDescGZIP() []byte {
	file_moderation_proto_rawDescOnce.Do(func() {
		file_moderation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moderation_proto_rawDesc), len(file_moderation_proto_rawDesc)))
	})
	return file_moderation_proto_rawDescData
}

var file_moderation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_moderation_proto_goTypes = []any{
	(*PublishArticleRequest)(nil),  // 0: PublishArticleRequest
	(*PublishArticleResponse)(nil), // 1: PublishArticleResponse
}
var file_moderation_proto_depIdxs = []int32{
	0, // 0: ModerationService.PublishArticle:input_type -> PublishArticleRequest
	1, // 1: ModerationService.PublishArticle:output_type -> PublishArticleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_moderation_proto_init() }
func file_moderation_proto_init() {
	if File_moderation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moderation_proto_rawDesc), len(file_moderation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moderation_proto_goTypes,
		DependencyIndexes: file_moderation_proto_depIdxs,
		MessageInfos:      file_moderation_proto_msgTypes,
	}.Build()
	File_moderation_proto = out.File
	file_moderation_proto_goTypes = nil
	file_moderation_proto_depIdxs = nil
}
