global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    # Default :80
    address: :8081 # change to :8081 to avoid port conflict with valet

  websecure:
    # Default :443
    address: :8443 # change to :8443 to avoid port conflict with valet

  grpc:
    address: :9000

api:
  insecure: true

providers:
  consulCatalog:
    defaultRule: "Host(`{{ .Name }}.local`)"
    endpoint:
      address: "consul-server:8500"
    exposedByDefault: true