apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: arm64v8/mongo:8.0.12
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
          volumeMounts:
            - mountPath: /data/db
              name: mongo-pv
      volumes:
        - name: mongo-pv
          emptyDir: {}